### ISSUE TITLE
Show laser points with different colors for each laser

### ISSUE THREAD

**Issue by hellxberg** [hellxberg/location-atlascar2-images#1]

**Comment by hellxberg** [comment]
Each cloud points is overlaid on the IPM image.

![Overlay_of_each_clouds_IPM](https://user-images.githubusercontent.com/24720785/54619196-1f0e7a80-4a5c-11e9-8c6d-1c0324bf4d08.png)

**Comment by miguelriemoliveira** [comment]
Hi @hellxberg ,

looks better now. now show the polygons and the merged polygon ...
