### ISSUE TITLE
Multimodal IPM result using point in polygon test

### ISSUE THREAD

**Issue by hellxberg** [hellxberg/location-atlascar2-images#3]
This is version A of Multimodal IPM

**Comment by hellxberg** [comment]
I've attempted to apply the first approach of implementation of the multi-modal IPM. Being the first approach verifying if the coordinate of the IPM image is in the polygon. I got the following results:

![IPM_almost_multi_modal](https://user-images.githubusercontent.com/24720785/54694202-c1436680-4b1f-11e9-8158-6ac459cbf52d.jpeg)

It is visible on the non-interpolated IPM image that this method works but it takes a huge ammount of time. On the cycle that creates the "Mapx" and "Mapy" variables i takes 10 seconds to process the information while it took 0.2 seconds previously.

Besides the huge ammount of processing time there is another issue on the interpolation process. 

![interpolation](https://user-images.githubusercontent.com/24720785/54694542-4a5a9d80-4b20-11e9-837e-76f01589fef1.jpeg)
 
Even though there is a big chunk of missing information in the middle of the IPM image it is still interpolated and i don't know how to solve it. @miguelriemoliveira Do you have any ideas of how to solve this? I will create a new issue about this.

**Comment by miguelriemoliveira** [comment]
Looks good. Keep up the good work.

Miguel
